// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID              pgtype.UUID
	UserID          pgtype.UUID
	LedgerAccountID pgtype.UUID
	CreatedAt       pgtype.Timestamptz
}
